version: '2'

services:
  orderer.example.com:
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050
    extends:
      file: ./peer-base.yaml
      service: orderer-base
    volumes:
      - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/:/var/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 8443:8443
  orderer2.example.com:
    environment: 
      - ORDERER_GENERAL_LISTENPORT=8050
    extends: 
      file: peer-base.yaml
      service: orderer-base
    volumes: 
      - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/:/var/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.example.com:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
      - 8444:8443

  orderer3.example.com:
    environment: 
      - ORDERER_GENERAL_LISTENPORT=9050
    extends: 
      file: peer-base.yaml
      service: orderer-base
    volumes: 
      - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/:/var/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer3.example.com:/var/hyperledger/production/orderer
    ports:
      - 9050:9050
      - 8445:8443
